### ISSUE TITLE
False positive warning when pasting BSLightingShaderProperty

### ISSUE THREAD

**Issue by GammaMetroid** [gavrant/nifskope#5]
Pasting a BSLightingShaderProperty in a Skyrim nif shows the following warning:
> NiTriShape [2]\Shader Property: Could not find "Shader Property" subitem.

Everything seems to work as expected though so it looks like a false positive?

**Comment by gavrant** [comment]
Hmm, can't reproduce the message. Just to make sure, we are talking about an Oldrim (pre-SE Skyrim) mesh, and copying via right context menu -> "Block" -> "Copy" or "Copy Branch", then pasting via "Paste" or "Paste Over" from the same menu? Tried that and also Ctrl+C - Ctrl+V, got no error messages.

And judging by the NiTriShape having such a low index of 2, were you editing a freshly imported mesh, by chance? If yes, could it be that the Version in the header was still the default ancient 20.0.0.5? Or maybe I should look at a particular mesh?

**Comment by GammaMetroid** [comment]
Ah it seems to happen only when I paste directly onto the Shader Property field of the TriShape. Pasting onto the TriShape block itself does not show the message.

**Comment by gavrant** [comment]
OK, pasting over "Shader Property" field gives me the message too, will fix that soon.

**Comment by gavrant** [comment]
It turned out there were quite a few things that could be fixed or improved in the pasting routine (or more generally, "attach block to block" routine) besides the parsing warning. To quote the commit message:
> Expanded the number of supported "child block - target block" combinations. It now auto-fills the following fields in the target block if the inserted child block is of a suitable type: "Data", "Skin" or "Skin Instance" in shapes; "Data" and "Skin Partition" in skin instances; "Texture Set" in shaders; "Body", "Shape" and "Data" in collisions.

The field list above is not exhaustive, I may have missed other good auto-fill fields options. If you find ones, please create a new ticket.

I will make a release with this fix included in a few days (need to polish some other stuff first before publishing).
